### ISSUE TITLE
Issue with FIRST in IDA 7.3

### ISSUE THREAD

**Issue by recvfrom** [vrtadmin/FIRST-plugin-ida#25]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:/Program Files/IDA Pro 7.3/plugins/first.py", line 2596, in __thread_scan
    architecture = FIRST.Info.get_architecture()
  File "C:/Program Files/IDA Pro 7.3/plugins/first.py", line 1019, in get_architecture
    if info.is_64bit():
  File "C:\Program Files\IDA Pro 7.3\python\ida_ida.py", line 2943, in __func
    return func(*args)
  File "C:\Program Files\IDA Pro 7.3\python\ida_ida.py", line 997, in inf_is_64bit
    return _ida_ida.inf_is_64bit(*args)
RuntimeError: Function can be called from the main thread only
```

**Comment by recvfrom** [comment]
Now the dev has been merged into master, this ticket can be closed
